[project]
name = "tractive-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rexchoppers", email = "rexchoppers@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiotractive>=1.0.3",
    "mcp[cli]>=1.27.0",
]

[project.scripts]
tractive-mcp = "tractive_mcp.server:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
